Docker, fix vue@2

diff --git a/.docker/Dockerfile b/.docker/Dockerfile
--- a/.docker/Dockerfile
+++ b/.docker/Dockerfile
@@ -1,8 +1,24 @@
-FROM gradle:7.4.1-jdk17-alpine as build
+FROM gradle:7.4.1-jdk11-alpine as build
 
+RUN gradle --version && java -version
+
+# Only copy dependency-related files
+COPY --chown=gradle:gradle build.gradle settings.gradle /app/
+
+# Only download dependencies
+# Eat the expected build failure since no source code has been copied yet
+RUN gradle clean build --no-daemon > /dev/null 2>&1 || true
+
+# Copy all/ remaining files
 COPY --chown=gradle:gradle . /home/gradle/src
-WORKDIR --/hom/gradle/src
+
+WORKDIR /home/gradle/src
+
 RUN gradle bootJar --no-daemon
 
-EXPOSE 80
-ENTRYPOINT ["dotnet", "Lott.Api.Retail.dll","--urls", "http://+:80"]
+FROM azul/zulu-openjdk-alpine:11.0.12
+
+COPY --from=build /home/gradle/src/build/libs/*.jar /app/
+
+EXPOSE 9091
+ENTRYPOINT ["java","-jar","-Dspring.profiles.active=n1","/app/bus-1.0.0.jar"]
